//! Golden XML output of the generators (templates and splice edits).
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::io::Write;

use goldenfile::Mint;
use rimstudio_core::load_plan::{LoadEntry, LoadFoldersSpec};
use rimstudio_core::mods::ModDependency;
use rimstudio_core::tree::NodeBuilder;
use rimstudio_xml::about::{AboutSpec, render_about};
use rimstudio_xml::load_folders::{create, gate_folder};
use rimstudio_xml::mods_config::{ModsConfigData, write_active};
use rimstudio_xml::render::{LineEnding, RenderOpts, Section, render_list_file, render_patch_file};

fn mint() -> Mint {
    Mint::new("tests/golden")
}

#[test]
fn new_about_file() {
    let mut mint = mint();
    let mut f = mint.new_goldenfile("about_new.xml").unwrap();
    let spec = AboutSpec {
        name: "RS Golden Mod".into(),
        author: "Ann".into(),
        package_id: "rs.golden".into(),
        description: "First line\nSecond line with <markup> & ampersand".into(),
        supported_versions: vec!["1.5".into(), "1.6".into()],
        url: Some("https://example.invalid/golden".into()),
        mod_dependencies: vec![ModDependency {
            package_id: "rs.base".into(),
            display_name: "RS Base".into(),
            steam_workshop_url: Some("steam://url/CommunityFilePage/1".into()),
            alternatives: vec!["rs.base.alt".into()],
            ..ModDependency::default()
        }],
        load_after: vec!["ludeon.rimworld".into(), "rs.base".into()],
        load_before: vec![],
        incompatible_with: vec!["rs.clash".into()],
        mod_version: Some("0.1.0".into()),
    };
    f.write_all(render_about(&spec, &RenderOpts::default()).as_bytes())
        .unwrap();
}

#[test]
fn new_load_folders_with_gated_folder() {
    let mut mint = mint();
    let mut f = mint.new_goldenfile("load_folders_new.xml").unwrap();
    let spec = LoadFoldersSpec::from_blocks([
        ("1.5", vec![LoadEntry::root()]),
        (
            "1.6",
            vec![
                LoadEntry::root(),
                LoadEntry::dir("CE").if_active(["rs.fictional.combat"]),
                LoadEntry::dir("NoCE").if_not_active(["rs.fictional.combat"]),
            ],
        ),
    ]);
    f.write_all(create(&spec, &RenderOpts::default()).as_bytes())
        .unwrap();
}

#[test]
fn gated_folder_spliced_into_a_hand_written_file() {
    let mut mint = mint();
    let mut f = mint.new_goldenfile("load_folders_spliced.xml").unwrap();
    let src = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- written by hand -->\n<loadFolders>\n    <v1.6>\n        <li>/</li>\n        <li>1.6</li>\n    </v1.6>\n</loadFolders>\n";
    let out = gate_folder(src, "1.6", "CE", &["rs.fictional.combat"]).unwrap();
    f.write_all(out.as_bytes()).unwrap();
}

#[test]
fn mods_config_rewritten_in_place() {
    let mut mint = mint();
    let mut f = mint.new_goldenfile("mods_config_written.xml").unwrap();
    let src = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<ModsConfigData>\n  <version>1.6.0000 rev0</version>\n  <activeMods>\n    <li>ludeon.rimworld</li>\n  </activeMods>\n  <!-- tool added -->\n  <knownExpansions />\n</ModsConfigData>\n";
    let data = ModsConfigData {
        version: Some("1.6.1111 rev1".into()),
        active_mods: vec![
            "ludeon.rimworld".into(),
            "rs.alpha".into(),
            "rs.beta_steam".into(),
        ],
        known_expansions: Some(vec!["ludeon.rimworld.royalty".into()]),
    };
    f.write_all(write_active(src, &data).unwrap().as_bytes())
        .unwrap();
}

#[test]
fn defs_file_with_section_headers() {
    let mut mint = mint();
    let mut f = mint.new_goldenfile("defs_sections.xml").unwrap();
    let gun = NodeBuilder::new("ThingDef")
        .attr("ParentName", "RS_BaseGun")
        .text_elem("defName", "RS_TestRifle")
        .text_elem("label", "test rifle")
        .elem("statBases", |b| {
            b.text_elem("Mass", "3.5").text_elem("MarketValue", "250")
        })
        .elem("verbs", |b| b.elem("li", |l| l.text_elem("range", "30.9")))
        .build();
    let tools = [NodeBuilder::new("ThingDef")
        .text_elem("defName", "RS_TestKnife")
        .build()];
    let guns = [gun];
    let opts = RenderOpts {
        blank_line_between_top_level: true,
        eol: LineEnding::Lf,
        ..RenderOpts::default()
    };
    let text = render_list_file(
        "Defs",
        &[
            Section::with_comment("Ranged weapons", &guns),
            Section::with_comment("Melee weapons\nGenerated by a test", &tools),
        ],
        &opts,
    );
    f.write_all(text.as_bytes()).unwrap();
}

#[test]
fn patch_file_for_a_gated_folder() {
    let mut mint = mint();
    let mut f = mint.new_goldenfile("patch_file.xml").unwrap();
    let op = NodeBuilder::new("Operation")
        .attr("Class", "PatchOperationReplace")
        .text_elem(
            "xpath",
            "Defs/ThingDef[defName=\"RS_TestRifle\"]/statBases/Mass",
        )
        .elem("value", |v| v.text_elem("Mass", "3.2"))
        .build();
    f.write_all(render_patch_file(&[op], &RenderOpts::default()).as_bytes())
        .unwrap();
}
