// Generated by `cargo test -p rimstudio-app --test bindings`. Do not edit.
// Refresh: UPDATE_BINDINGS=1 cargo test -p rimstudio-app --test bindings

import type {
  AppGetInfoRequest,
  AppGetInfoResponse,
  AppListToolsRequest,
  AppListToolsResponse,
  AppPingRequest,
  AppPingResponse,
  ApplyReportDto,
  CalibrateResultDto,
  CancelJobRequest,
  CancelJobResponse,
  CeSuggestionDto,
  ConvertScanDto,
  DefPage,
  DefSearchRequest,
  DefsGetResolvedRequest,
  DesignerApplyPlanRequest,
  DesignerAssetInfoRequest,
  DesignerAssetInfoResponse,
  DesignerCalibrateRequest,
  DesignerCeSuggestRequest,
  DesignerCloneDiffRequest,
  DesignerCloneDiffResponse,
  DesignerCloneRequest,
  DesignerCloneResponse,
  DesignerConvertScanRequest,
  DesignerDraftDeleteRequest,
  DesignerDraftDeleteResponse,
  DesignerDraftListRequest,
  DesignerDraftListResponse,
  DesignerDraftSaveRequest,
  DesignerDraftSaveResponse,
  DesignerExportPlanRequest,
  DesignerFitRequest,
  DesignerPreviewRequest,
  DesignerProjectileOwnRequest,
  DesignerProjectileOwnResponse,
  DesignerQuizAnswerRequest,
  DesignerQuizAnswerResponse,
  DesignerQuizBackRequest,
  DesignerQuizNextRequest,
  DesignerReferenceListRequest,
  DesignerStructureDefaultsRequest,
  DesignerStructureDefaultsResponse,
  DetectGetReportRequest,
  DetectGetReportResponse,
  DetectRunRequest,
  DetectSetOverrideRequest,
  DetectionReportDto,
  FitReportDto,
  JobStatusRequest,
  JobStatusResponse,
  LibraryScanRequest,
  LibraryScanResult,
  PreviewDto,
  ProjectCloseRequest,
  ProjectCloseResponse,
  ProjectCreateRequest,
  ProjectFileDto,
  ProjectLayoutCheckDto,
  ProjectLayoutCheckRequest,
  ProjectOpenRequest,
  ProjectReadFileRequest,
  ProjectScaffoldMissingDto,
  ProjectScaffoldMissingRequest,
  ProjectSummaryDto,
  ProjectTreeDto,
  ProjectTreeRequest,
  QuizStepDto,
  ReferenceListDto,
  ResolvedDefDto,
  SettingsDto,
  SettingsGetRequest,
  SettingsUpdate,
  SourceDto,
  SourcesAddFolderRequest,
  SourcesListRequest,
  SourcesListResponse,
  SourcesProbeFolderRequest,
  SourcesProbeFolderResponse,
  SourcesRemoveRequest,
  SourcesRemoveResponse,
  SourcesUpdateRequest,
  WritePlanDto,
} from "./bindings";

/** How a command is wired: `query` and `action` answer inline, `job` returns a handle and ends with one terminal event, `stream` is a long lived channel. */
export type CommandKind = "query" | "action" | "job" | "stream";

/** Request, response and kind of every command. For a job the response is the result carried by its terminal event. */
export interface CommandTable {
  app_ping: { kind: "query"; request: AppPingRequest; response: AppPingResponse };
  app_get_info: { kind: "query"; request: AppGetInfoRequest; response: AppGetInfoResponse };
  app_list_tools: { kind: "query"; request: AppListToolsRequest; response: AppListToolsResponse };
  cancel_job: { kind: "action"; request: CancelJobRequest; response: CancelJobResponse };
  job_status: { kind: "query"; request: JobStatusRequest; response: JobStatusResponse };
  settings_get: { kind: "query"; request: SettingsGetRequest; response: SettingsDto };
  settings_update: { kind: "action"; request: SettingsUpdate; response: SettingsDto };
  detect_run: { kind: "job"; request: DetectRunRequest; response: DetectionReportDto };
  detect_get_report: { kind: "query"; request: DetectGetReportRequest; response: DetectGetReportResponse };
  detect_set_override: { kind: "action"; request: DetectSetOverrideRequest; response: DetectGetReportResponse };
  sources_list: { kind: "query"; request: SourcesListRequest; response: SourcesListResponse };
  sources_add_folder: { kind: "action"; request: SourcesAddFolderRequest; response: SourceDto };
  sources_update: { kind: "action"; request: SourcesUpdateRequest; response: SourceDto };
  sources_remove: { kind: "action"; request: SourcesRemoveRequest; response: SourcesRemoveResponse };
  sources_probe_folder: { kind: "query"; request: SourcesProbeFolderRequest; response: SourcesProbeFolderResponse };
  library_scan: { kind: "job"; request: LibraryScanRequest; response: LibraryScanResult };
  defs_search: { kind: "query"; request: DefSearchRequest; response: DefPage };
  defs_get_resolved: { kind: "query"; request: DefsGetResolvedRequest; response: ResolvedDefDto };
  project_open: { kind: "action"; request: ProjectOpenRequest; response: ProjectSummaryDto };
  project_create: { kind: "action"; request: ProjectCreateRequest; response: ProjectSummaryDto };
  project_close: { kind: "action"; request: ProjectCloseRequest; response: ProjectCloseResponse };
  project_tree: { kind: "query"; request: ProjectTreeRequest; response: ProjectTreeDto };
  project_layout_check: { kind: "query"; request: ProjectLayoutCheckRequest; response: ProjectLayoutCheckDto };
  project_scaffold_missing: { kind: "action"; request: ProjectScaffoldMissingRequest; response: ProjectScaffoldMissingDto };
  project_read_file: { kind: "query"; request: ProjectReadFileRequest; response: ProjectFileDto };
  designer_reference_list: { kind: "query"; request: DesignerReferenceListRequest; response: ReferenceListDto };
  designer_preview: { kind: "query"; request: DesignerPreviewRequest; response: PreviewDto };
  designer_fit: { kind: "query"; request: DesignerFitRequest; response: FitReportDto };
  designer_ce_suggest: { kind: "query"; request: DesignerCeSuggestRequest; response: CeSuggestionDto };
  designer_quiz_next: { kind: "query"; request: DesignerQuizNextRequest; response: QuizStepDto };
  designer_quiz_answer: { kind: "action"; request: DesignerQuizAnswerRequest; response: DesignerQuizAnswerResponse };
  designer_quiz_back: { kind: "action"; request: DesignerQuizBackRequest; response: DesignerQuizAnswerResponse };
  designer_calibrate: { kind: "job"; request: DesignerCalibrateRequest; response: CalibrateResultDto };
  designer_convert_scan: { kind: "job"; request: DesignerConvertScanRequest; response: ConvertScanDto };
  designer_export_plan: { kind: "query"; request: DesignerExportPlanRequest; response: WritePlanDto };
  designer_apply_plan: { kind: "job"; request: DesignerApplyPlanRequest; response: ApplyReportDto };
  designer_draft_save: { kind: "action"; request: DesignerDraftSaveRequest; response: DesignerDraftSaveResponse };
  designer_draft_list: { kind: "query"; request: DesignerDraftListRequest; response: DesignerDraftListResponse };
  designer_draft_delete: { kind: "action"; request: DesignerDraftDeleteRequest; response: DesignerDraftDeleteResponse };
  designer_clone: { kind: "action"; request: DesignerCloneRequest; response: DesignerCloneResponse };
  designer_clone_diff: { kind: "query"; request: DesignerCloneDiffRequest; response: DesignerCloneDiffResponse };
  designer_structure_defaults: { kind: "query"; request: DesignerStructureDefaultsRequest; response: DesignerStructureDefaultsResponse };
  designer_projectile_own: { kind: "query"; request: DesignerProjectileOwnRequest; response: DesignerProjectileOwnResponse };
  designer_asset_info: { kind: "query"; request: DesignerAssetInfoRequest; response: DesignerAssetInfoResponse };
}

export type CommandName = keyof CommandTable;
export type CommandRequest<N extends CommandName> = CommandTable[N]["request"];
export type CommandResponse<N extends CommandName> = CommandTable[N]["response"];
export type CommandKindOf<N extends CommandName> = CommandTable[N]["kind"];
export type CommandsOfKind<K extends CommandKind> = {
  [N in CommandName]: CommandKindOf<N> extends K ? N : never;
}[CommandName];

/** One entry of the command list: the wire name and the kind. */
export interface CommandEntry<N extends CommandName = CommandName> {
  readonly name: N;
  readonly kind: CommandKindOf<N>;
}

/** Every command by its camelCase export name. */
export const commands = {
  appPing: { name: "app_ping", kind: "query" },
  appGetInfo: { name: "app_get_info", kind: "query" },
  appListTools: { name: "app_list_tools", kind: "query" },
  cancelJob: { name: "cancel_job", kind: "action" },
  jobStatus: { name: "job_status", kind: "query" },
  settingsGet: { name: "settings_get", kind: "query" },
  settingsUpdate: { name: "settings_update", kind: "action" },
  detectRun: { name: "detect_run", kind: "job" },
  detectGetReport: { name: "detect_get_report", kind: "query" },
  detectSetOverride: { name: "detect_set_override", kind: "action" },
  sourcesList: { name: "sources_list", kind: "query" },
  sourcesAddFolder: { name: "sources_add_folder", kind: "action" },
  sourcesUpdate: { name: "sources_update", kind: "action" },
  sourcesRemove: { name: "sources_remove", kind: "action" },
  sourcesProbeFolder: { name: "sources_probe_folder", kind: "query" },
  libraryScan: { name: "library_scan", kind: "job" },
  defsSearch: { name: "defs_search", kind: "query" },
  defsGetResolved: { name: "defs_get_resolved", kind: "query" },
  projectOpen: { name: "project_open", kind: "action" },
  projectCreate: { name: "project_create", kind: "action" },
  projectClose: { name: "project_close", kind: "action" },
  projectTree: { name: "project_tree", kind: "query" },
  projectLayoutCheck: { name: "project_layout_check", kind: "query" },
  projectScaffoldMissing: { name: "project_scaffold_missing", kind: "action" },
  projectReadFile: { name: "project_read_file", kind: "query" },
  designerReferenceList: { name: "designer_reference_list", kind: "query" },
  designerPreview: { name: "designer_preview", kind: "query" },
  designerFit: { name: "designer_fit", kind: "query" },
  designerCeSuggest: { name: "designer_ce_suggest", kind: "query" },
  designerQuizNext: { name: "designer_quiz_next", kind: "query" },
  designerQuizAnswer: { name: "designer_quiz_answer", kind: "action" },
  designerQuizBack: { name: "designer_quiz_back", kind: "action" },
  designerCalibrate: { name: "designer_calibrate", kind: "job" },
  designerConvertScan: { name: "designer_convert_scan", kind: "job" },
  designerExportPlan: { name: "designer_export_plan", kind: "query" },
  designerApplyPlan: { name: "designer_apply_plan", kind: "job" },
  designerDraftSave: { name: "designer_draft_save", kind: "action" },
  designerDraftList: { name: "designer_draft_list", kind: "query" },
  designerDraftDelete: { name: "designer_draft_delete", kind: "action" },
  designerClone: { name: "designer_clone", kind: "action" },
  designerCloneDiff: { name: "designer_clone_diff", kind: "query" },
  designerStructureDefaults: { name: "designer_structure_defaults", kind: "query" },
  designerProjectileOwn: { name: "designer_projectile_own", kind: "query" },
  designerAssetInfo: { name: "designer_asset_info", kind: "query" },
} as const satisfies Record<string, CommandEntry>;

/** Every wire name, in registry order. */
export const commandNames = [
  "app_ping",
  "app_get_info",
  "app_list_tools",
  "cancel_job",
  "job_status",
  "settings_get",
  "settings_update",
  "detect_run",
  "detect_get_report",
  "detect_set_override",
  "sources_list",
  "sources_add_folder",
  "sources_update",
  "sources_remove",
  "sources_probe_folder",
  "library_scan",
  "defs_search",
  "defs_get_resolved",
  "project_open",
  "project_create",
  "project_close",
  "project_tree",
  "project_layout_check",
  "project_scaffold_missing",
  "project_read_file",
  "designer_reference_list",
  "designer_preview",
  "designer_fit",
  "designer_ce_suggest",
  "designer_quiz_next",
  "designer_quiz_answer",
  "designer_quiz_back",
  "designer_calibrate",
  "designer_convert_scan",
  "designer_export_plan",
  "designer_apply_plan",
  "designer_draft_save",
  "designer_draft_list",
  "designer_draft_delete",
  "designer_clone",
  "designer_clone_diff",
  "designer_structure_defaults",
  "designer_projectile_own",
  "designer_asset_info",
] as const satisfies readonly CommandName[];
