//! Rendering of planned files and byte span merging into files that already exist.
//!
//! A planned file carries a node tree and comment headers ([`PlannedFile::section_groups`]). A file that does
//! not exist is rendered whole by `rimstudio-xml`. A file that exists is changed by splicing: the section of
//! the design (found by its `====== Name ======` comment) is replaced in place, a definition with the same
//! name is replaced as an element, and anything new is appended before the closing tag, in the indentation
//! and line ending of the file. Every byte outside the changed span stays as it was (IT-053). `LoadFolders.xml`
//! is edited with the entry functions of `rimstudio-xml`.
//!
//! All functions return `Err(reason)` with a plain sentence when the existing file cannot be merged (not
//! well formed, another root element); the planner turns that into a diagnostic and plans nothing for it.

use rimstudio_core::load_plan::LoadEntry;
use rimstudio_core::tree::Node;
use rimstudio_design::plan::{PlannedFile, SectionGroup, TextEdit};
use rimstudio_xml::edit::SpanEditor;
use rimstudio_xml::load_folders::{add_entry, ensure_block};
use rimstudio_xml::render::{RenderOpts, Section, render_list_file};

/// The marker that starts a section comment of RimStudio output.
const BANNER: &str = "======";

/// The text of a new file: the root element of the planned tree with its section comments.
#[must_use]
pub fn render_new(file: &PlannedFile) -> String {
    let Some(tree) = &file.tree else {
        return String::new();
    };
    let groups = file.section_groups();
    let sections: Vec<Section<'_>> = groups
        .iter()
        .map(|g| Section {
            comment: g.comment.as_deref(),
            nodes: &g.nodes,
        })
        .collect();
    render_list_file(&tree.tag, &sections, &RenderOpts::default())
}

/// The part of a section comment that names the section: `====== Name ======` out of
/// `====== Name ====== generated by ...`.
fn banner_key(comment: &str) -> Option<&str> {
    if !comment.starts_with(BANNER) {
        return None;
    }
    let rest = comment.get(BANNER.len()..)?;
    let end = rest.find(BANNER)?;
    comment.get(..BANNER.len() + end + BANNER.len())
}

/// The lines of one section as it should stand inside a document with the given indent unit: the comment
/// and the nodes, one level below the root.
fn section_lines(root_tag: &str, group: &SectionGroup, unit: &str) -> Vec<String> {
    let opts = RenderOpts {
        declaration: false,
        final_newline: false,
        ..RenderOpts::default()
    };
    let doc = render_list_file(
        root_tag,
        &[Section {
            comment: group.comment.as_deref(),
            nodes: &group.nodes,
        }],
        &opts,
    );
    let lines: Vec<&str> = doc.split('\n').collect();
    let inner = lines.get(1..lines.len().saturating_sub(1)).unwrap_or(&[]);
    inner
        .iter()
        .map(|line| {
            let mut level = 0usize;
            let mut rest: &str = line;
            while let Some(r) = rest.strip_prefix("  ") {
                level += 1;
                rest = r;
            }
            format!("{}{rest}", unit.repeat(level))
        })
        .collect()
}

fn open(text: &str) -> Result<SpanEditor, String> {
    SpanEditor::open(text).map_err(|e| format!("the existing file cannot be edited: {e}"))
}

/// The byte offset of the closing tag of the root element.
fn close_start(text: &str, root_end: usize) -> usize {
    text.get(..root_end)
        .and_then(|t| t.rfind('<'))
        .unwrap_or(root_end)
}

fn merge_group(text: &str, root_tag: &str, group: &SectionGroup) -> Result<String, String> {
    let ed = open(text)?;
    if ed.root_tag() != root_tag {
        return Err(format!(
            "the existing file has the root element {} but the plan needs {root_tag}",
            ed.root_tag()
        ));
    }
    let root_path = format!("/{root_tag}");
    let info = ed.element(&root_path).map_err(|e| e.to_string())?;
    let eol = ed.eol();
    let unit = ed.indent_unit();
    let unit = if unit.is_empty() {
        "  ".to_owned()
    } else {
        unit
    };
    let bom = if text.starts_with('\u{feff}') {
        "\u{feff}"
    } else {
        ""
    };

    // an empty root has nothing to keep: write the section as a fresh document
    if info.child_count == 0 {
        let fresh = render_list_file(
            root_tag,
            &[Section {
                comment: group.comment.as_deref(),
                nodes: &group.nodes,
            }],
            &RenderOpts::default(),
        );
        return Ok(format!("{bom}{}", fresh.replace('\n', eol)));
    }

    let lines = section_lines(root_tag, group, &unit);

    // 1. the section of an earlier export of the same item is replaced in place
    if let Some(key) = group.comment.as_deref().and_then(banner_key) {
        let needle = format!("<!-- {key}");
        if let Some(pos) = text.find(&needle) {
            let comment_end = text
                .get(pos..)
                .and_then(|t| t.find("-->"))
                .map_or(pos + needle.len(), |i| pos + i + 3);
            let limit = if root_tag == "Defs" {
                group.nodes.len().max(1)
            } else {
                usize::MAX
            };
            // outside `Defs` the section has no fixed length: it is the run of elements after the banner
            // that mention the item's name (every generated operation does). An element that does not,
            // such as an operation the person wrote by hand, ends the section and is kept.
            let item = key.trim_matches(|c: char| c == '=' || c == ' ');
            let mut end = comment_end;
            let mut count = 0usize;
            if let Ok(kids) = ed.children(&root_path) {
                for kid in kids {
                    let Ok(child) = ed.element(&kid.path) else {
                        continue;
                    };
                    if child.span.start < pos {
                        continue;
                    }
                    let gap = text.get(end..child.span.start).unwrap_or("");
                    if count >= limit || gap.contains("<!--") {
                        break;
                    }
                    if root_tag != "Defs"
                        && !item.is_empty()
                        && !text
                            .get(child.span.clone())
                            .is_some_and(|t| t.contains(item))
                    {
                        break;
                    }
                    end = child.span.end;
                    count += 1;
                }
            }
            let joined = lines.join(eol);
            let body = joined.trim_start();
            let mut out = String::with_capacity(text.len() + body.len());
            out.push_str(text.get(..pos).unwrap_or(""));
            out.push_str(body);
            out.push_str(text.get(end..).unwrap_or(""));
            open(&out)?;
            return Ok(out);
        }
    }

    // 2. a definition of the same name is replaced as an element
    let mut text = text.to_owned();
    let mut remaining: Vec<&Node> = Vec::new();
    if root_tag == "Defs" {
        let mut ed = open(&text)?;
        for node in &group.nodes {
            let name = node.child_text("defName");
            let found = name.and_then(|n| {
                ed.children(&root_path).ok().and_then(|kids| {
                    kids.into_iter()
                        .filter(|k| k.tag == node.tag)
                        .find(|k| {
                            ed.element_text(&format!("{}/defName", k.path))
                                .is_ok_and(|t| t.trim() == n)
                        })
                        .map(|k| k.path)
                })
            });
            match found {
                Some(path) => {
                    ed.replace_element(&path, node).map_err(|e| e.to_string())?;
                }
                None => remaining.push(node),
            }
        }
        text = ed.into_text();
        if remaining.is_empty() {
            return Ok(text);
        }
    }

    // 3. the new section is appended before the closing tag
    let ed = open(&text)?;
    let info = ed.element(&root_path).map_err(|e| e.to_string())?;
    let close = close_start(&text, info.span.end);
    let lines = if remaining.is_empty() {
        lines
    } else {
        let rest = SectionGroup {
            comment: group.comment.clone(),
            nodes: remaining.into_iter().cloned().collect(),
        };
        section_lines(root_tag, &rest, &unit)
    };
    let cut = text.get(..close).map_or(close, |t| t.trim_end().len());
    let mut out = String::with_capacity(text.len() + 256);
    out.push_str(text.get(..cut).unwrap_or(""));
    out.push_str(eol);
    out.push_str(&lines.join(eol));
    out.push_str(text.get(cut..).unwrap_or(""));
    open(&out)?;
    Ok(out)
}

/// Merges the sections of a planned list file (a `Defs` or `Patch` root) into the existing text.
///
/// # Errors
///
/// A plain sentence when the existing text is not well formed or has another root element.
pub fn merge_into(existing: &str, file: &PlannedFile) -> Result<String, String> {
    let Some(tree) = &file.tree else {
        return Err("the planned file has no tree".to_owned());
    };
    let mut text = existing.to_owned();
    for group in file.section_groups() {
        text = merge_group(&text, &tree.tag, &group)?;
    }
    Ok(text)
}

fn ids(value: &str) -> Vec<String> {
    value
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect()
}

fn entry_of(li: &Node) -> LoadEntry {
    let text = li.text_content();
    let text = text.trim();
    let mut entry = if text.is_empty() || text == "/" || text == "\\" {
        LoadEntry::root()
    } else {
        LoadEntry::dir(text)
    };
    if let Some(v) = li.attr("IfModActive") {
        entry = entry.if_active(ids(v));
    }
    if let Some(v) = li.attr("IfModActiveAll") {
        entry = entry.if_active_all(ids(v));
    }
    if let Some(v) = li.attr("IfModNotActive") {
        entry = entry.if_not_active(ids(v));
    }
    entry
}

/// Applies the blocks and entries of a planned `LoadFolders.xml` tree to the existing text: a missing block
/// is created as a copy of the nearest lower block (else `default`, else the planned entries), a missing entry
/// is appended to its block, and nothing else changes.
///
/// # Errors
///
/// A plain sentence when the existing text cannot be edited.
pub fn merge_load_folders(existing: &str, planned: &Node) -> Result<String, String> {
    let mut text = existing.to_owned();
    for block in planned.elements() {
        let entries: Vec<LoadEntry> = block.children_named("li").map(entry_of).collect();
        text = ensure_block(&text, &block.tag, &entries)
            .map_err(|e| format!("LoadFolders.xml cannot be edited: {e}"))?;
        for entry in &entries {
            text = add_entry(&text, &block.tag, entry)
                .map_err(|e| format!("LoadFolders.xml cannot be edited: {e}"))?;
        }
    }
    Ok(text)
}

/// The single byte span that turns `old` into `new` (common prefix and suffix trimmed), empty when equal.
#[must_use]
pub fn changed_span(old: &str, new: &str) -> Vec<TextEdit> {
    if old == new {
        return Vec::new();
    }
    let ob = old.as_bytes();
    let nb = new.as_bytes();
    let mut prefix = 0usize;
    while prefix < ob.len() && prefix < nb.len() && ob.get(prefix) == nb.get(prefix) {
        prefix += 1;
    }
    while !old.is_char_boundary(prefix) || !new.is_char_boundary(prefix) {
        prefix -= 1;
    }
    let mut suffix = 0usize;
    while suffix < ob.len() - prefix
        && suffix < nb.len() - prefix
        && ob.get(ob.len() - 1 - suffix) == nb.get(nb.len() - 1 - suffix)
    {
        suffix += 1;
    }
    while !old.is_char_boundary(ob.len() - suffix) || !new.is_char_boundary(nb.len() - suffix) {
        suffix -= 1;
    }
    vec![TextEdit {
        start: prefix,
        end: ob.len() - suffix,
        replacement: new
            .get(prefix..nb.len() - suffix)
            .unwrap_or_default()
            .to_owned(),
    }]
}

#[cfg(test)]
mod tests {
    use super::*;
    use rimstudio_core::tree::NodeBuilder;
    use rimstudio_design::plan::{FileKind, SectionHeader};

    fn defs_file(names: &[&str]) -> PlannedFile {
        let mut b = NodeBuilder::new("Defs");
        for n in names {
            b = b.elem("ThingDef", |t| {
                t.text_elem("defName", *n).text_elem("label", "v2")
            });
        }
        PlannedFile::new_file(
            "Defs/A.xml",
            FileKind::VanillaDefs,
            b.build(),
            vec![SectionHeader::banner(0, names[0])],
        )
    }

    #[test]
    fn a_new_file_has_declaration_and_section_comment() {
        let text = render_new(&defs_file(&["RS_A"]));
        assert!(text.starts_with("<?xml"));
        assert!(text.contains("<!-- ====== RS_A ====== -->"));
        assert!(text.contains("<defName>RS_A</defName>"));
    }

    #[test]
    fn a_section_of_an_earlier_export_is_replaced_and_other_bytes_stay() {
        let first = render_new(&defs_file(&["RS_A"]));
        // a hand made addition with odd white space and a comment
        let hand = first.replace(
            "</Defs>",
            "\n\n<!--   keep me   -->\n<ThingDef>\n\t<defName>RS_Hand</defName>\n</ThingDef>\n</Defs>",
        );
        let merged = merge_into(&hand, &defs_file(&["RS_A"])).unwrap();
        assert_eq!(merged, hand, "the same section changes nothing");
        let changed = defs_file(&["RS_A"]);
        let mut f = changed.clone();
        if let Some(tree) = f.tree.as_mut() {
            for child in tree.elements_mut() {
                child.set_child_text("label", "v3");
            }
        }
        let merged = merge_into(&hand, &f).unwrap();
        assert!(merged.contains("<label>v3</label>"));
        assert!(merged.contains("<!--   keep me   -->"));
        assert!(merged.contains("<defName>RS_Hand</defName>"));
        let edits = changed_span(&hand, &merged);
        assert_eq!(edits.len(), 1);
        let e = &edits[0];
        assert!(hand[..e.start] == merged[..e.start], "prefix is identical");
    }

    #[test]
    fn a_new_section_is_appended_in_the_style_of_the_file() {
        let existing = "<?xml version=\"1.0\"?>\r\n<Defs>\r\n\t<ThingDef>\r\n\t\t<defName>RS_Old</defName>\r\n\t</ThingDef>\r\n</Defs>\r\n";
        let merged = merge_into(existing, &defs_file(&["RS_New"])).unwrap();
        assert!(merged.starts_with(&existing[..existing.len() - "</Defs>\r\n".len() - 2]));
        assert!(merged.contains("\r\n\t<!-- ====== RS_New ====== -->\r\n\t<ThingDef>"));
        assert!(merged.ends_with("</Defs>\r\n"));
        assert!(!merged.replace("\r\n", "").contains('\n'));
    }

    #[test]
    fn an_unmarked_def_of_the_same_name_is_replaced_as_an_element() {
        let existing = "<Defs>\n  <ThingDef>\n    <defName>RS_A</defName>\n    <label>old</label>\n  </ThingDef>\n</Defs>\n";
        let merged = merge_into(existing, &defs_file(&["RS_A"])).unwrap();
        assert_eq!(merged.matches("<defName>RS_A</defName>").count(), 1);
        assert!(merged.contains("<label>v2</label>"));
    }

    #[test]
    fn another_root_element_or_broken_text_is_reported() {
        let f = defs_file(&["RS_A"]);
        assert!(merge_into("<Patch><x/></Patch>", &f).is_err());
        assert!(merge_into("<Defs><x></Defs>", &f).is_err());
    }

    #[test]
    fn an_empty_root_is_written_fresh_keeping_the_bom() {
        let merged = merge_into("\u{feff}<Defs/>", &defs_file(&["RS_A"])).unwrap();
        assert!(merged.starts_with('\u{feff}'));
        assert!(merged.contains("RS_A"));
    }

    #[test]
    fn load_folders_gets_the_block_and_the_gate_without_touching_the_rest() {
        let existing = "<!-- mine -->\n<loadFolders>\n  <v1.5>\n    <li>/</li>\n    <li>1.5</li>\n  </v1.5>\n</loadFolders>\n";
        let planned = NodeBuilder::new("loadFolders")
            .elem("v1.6", |b| b.li("/").li("1.5"))
            .build();
        let mut planned = planned;
        if let Some(block) = planned.elements_mut().next() {
            let mut gated = Node::with_text("li", "CE");
            gated.set_attr("IfModActive", "ceteam.combatextended");
            block.push_child(gated);
        }
        let merged = merge_load_folders(existing, &planned).unwrap();
        assert!(merged.starts_with("<!-- mine -->\n<loadFolders>\n  <v1.5>"));
        assert!(merged.contains("v1.6"));
        assert!(merged.contains("IfModActive=\"ceteam.combatextended\""));
        let again = merge_load_folders(&merged, &planned).unwrap();
        assert_eq!(again, merged, "merging twice changes nothing");
    }

    #[test]
    fn the_changed_span_is_minimal_and_char_safe() {
        assert!(changed_span("same", "same").is_empty());
        let e = changed_span("aXc", "abc");
        assert_eq!(
            (e[0].start, e[0].end, e[0].replacement.as_str()),
            (1, 2, "b")
        );
        let e = changed_span("a\u{e9}c", "a\u{e8}c");
        assert!(e[0].start <= 1 + 1);
        let mut text = "a\u{e9}c".to_owned();
        text.replace_range(e[0].start..e[0].end, &e[0].replacement);
        assert_eq!(text, "a\u{e8}c");
    }
}
