//! The optional Combat Extended patch in the plan: its own gated files, the LoadFolders cases, and the
//! gating rule over every plan (IT-052, IT-054).
#![cfg(feature = "tool-designer")]
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::print_stdout)]

mod common;
mod common_project;

use common_project::{
    assert_text_golden, fixture, melee, melee_ce, project, ranged, ranged_ce, request,
};
use rimstudio_ipc_types::designer::{FileActionDto, FileKindDto, WritePlanDto};
use rimstudio_toolkit::designer::export_plan;

const CE_MARK: &str = "CombatExtended.";

fn paths(plan: &WritePlanDto) -> Vec<&str> {
    plan.files.iter().map(|f| f.path.as_str()).collect()
}

fn assert_gated(plan: &WritePlanDto) {
    for f in &plan.files {
        if f.rendered.contains(CE_MARK) {
            assert_eq!(f.kind, FileKindDto::CePatch, "{} holds a CE class", f.path);
            assert!(
                f.path.starts_with("Compat/CombatExtended/"),
                "{} is outside the CE folder",
                f.path
            );
        }
    }
}

#[test]
fn the_ranged_block_adds_a_gated_patch_and_load_folders_and_keeps_the_vanilla_files() {
    let f = fixture(true);
    let p = project(&f, &[]);
    let off = export_plan(&f.ctx, request(&p, &ranged())).unwrap();
    let on = export_plan(&f.ctx, request(&p, &ranged_ce())).unwrap();
    assert!(!on.has_errors, "{:?}", on.diagnostics);
    // vanilla files are byte identical with and without the block
    for v in off
        .files
        .iter()
        .filter(|x| x.kind == FileKindDto::VanillaDefs)
    {
        let same = on.files.iter().find(|x| x.path == v.path).unwrap();
        assert_eq!(same.rendered, v.rendered, "{}", v.path);
    }
    assert!(
        paths(&on).contains(&"Compat/CombatExtended/Patches/testmod_Weapons_Ranged.xml"),
        "{:?}",
        paths(&on)
    );
    assert!(paths(&on).contains(&"LoadFolders.xml"));
    assert!(off.files.iter().all(|x| x.kind == FileKindDto::VanillaDefs));
    assert_gated(&on);
    let patch = on
        .files
        .iter()
        .find(|x| x.kind == FileKindDto::CePatch)
        .unwrap();
    assert!(patch.rendered.contains(CE_MARK));
    assert!(patch.rendered.contains("generated by RimStudio"));
    assert_text_golden("ce_ranged_patch.xml", &patch.rendered);
}

#[test]
fn the_melee_block_adds_a_gated_patch() {
    let f = fixture(true);
    let p = project(&f, &[]);
    let on = export_plan(&f.ctx, request(&p, &melee_ce())).unwrap();
    assert!(!on.has_errors, "{:?}", on.diagnostics);
    assert_gated(&on);
    let patch = on
        .files
        .iter()
        .find(|x| x.kind == FileKindDto::CePatch)
        .unwrap();
    assert!(patch.path.ends_with("Weapons_Melee.xml"), "{}", patch.path);
    assert_text_golden("ce_melee_patch.xml", &patch.rendered);
    let off = export_plan(&f.ctx, request(&p, &melee())).unwrap();
    assert!(off.files.iter().all(|x| !x.rendered.contains(CE_MARK)));
}

#[test]
fn load_folders_is_created_when_the_project_has_none() {
    let f = fixture(true);
    let p = project(&f, &[]);
    let plan = export_plan(&f.ctx, request(&p, &ranged_ce())).unwrap();
    let lf = plan
        .files
        .iter()
        .find(|x| x.path == "LoadFolders.xml")
        .unwrap();
    assert_eq!(lf.action, FileActionDto::Create);
    assert!(
        lf.rendered
            .contains("IfModActive=\"ceteam.combatextended\"")
    );
    assert_text_golden("load_folders_none.xml", &lf.rendered);
}

#[test]
fn load_folders_without_the_gate_is_edited_by_splice_and_gets_a_v16_block() {
    let f = fixture(true);
    let existing = "<!-- my folders -->\n<loadFolders>\n\t<v1.5>\n\t\t<li>/</li>\n\t\t<li>1.5</li>\n\t</v1.5>\n</loadFolders>\n";
    let p = project(&f, &[("LoadFolders.xml", existing)]);
    let plan = export_plan(&f.ctx, request(&p, &ranged_ce())).unwrap();
    assert!(!plan.has_errors, "{:?}", plan.diagnostics);
    let lf = plan
        .files
        .iter()
        .find(|x| x.path == "LoadFolders.xml")
        .unwrap();
    assert_eq!(lf.action, FileActionDto::UpdateRegion);
    assert!(
        lf.rendered
            .starts_with("<!-- my folders -->\n<loadFolders>\n\t<v1.5>"),
        "{}",
        lf.rendered
    );
    assert!(lf.rendered.contains("1.6"));
    assert!(lf.rendered.contains("ceteam.combatextended"));
    let diff = lf.diff.as_deref().unwrap();
    assert!(diff.contains("+"), "{diff}");
    assert!(!diff.contains("\n-\t<v1.5>"), "the old block stays: {diff}");
    assert_text_golden("load_folders_existing.xml", &lf.rendered);
}

#[test]
fn load_folders_that_already_gates_the_folder_is_unchanged() {
    let f = fixture(true);
    let existing = "<loadFolders>\n  <v1.6>\n    <li>/</li>\n    <li IfModActive=\"CETeam.CombatExtended\">CE</li>\n  </v1.6>\n</loadFolders>\n";
    let p = project(&f, &[("LoadFolders.xml", existing)]);
    let plan = export_plan(&f.ctx, request(&p, &ranged_ce())).unwrap();
    assert!(!plan.has_errors, "{:?}", plan.diagnostics);
    let lf = plan
        .files
        .iter()
        .find(|x| x.path == "LoadFolders.xml")
        .unwrap();
    assert_eq!(lf.action, FileActionDto::Unchanged);
    assert_eq!(lf.rendered, existing);
    assert!(lf.diff.is_none());
}

#[test]
fn a_second_weapon_is_added_to_the_existing_patch_file_without_touching_the_first() {
    use rimstudio_core::jobs::{CancelToken, NoopProgress};
    use rimstudio_ipc_types::designer::DesignerApplyPlanRequest;
    use rimstudio_toolkit::designer::apply_plan;
    let f = fixture(true);
    let p = project(&f, &[]);
    let first = request(&p, &ranged_ce());
    let plan = export_plan(&f.ctx, first.clone()).unwrap();
    apply_plan(
        &f.ctx,
        DesignerApplyPlanRequest {
            plan_id: plan.plan_id,
            request: first,
            backup: true,
            dry_apply: true,
        },
        &NoopProgress,
        &CancelToken::new(),
    )
    .unwrap();
    let patch_path = "Compat/CombatExtended/Patches/testmod_Weapons_Ranged.xml";
    let before = std::fs::read_to_string(p.root.join(patch_path).as_std_path()).unwrap();
    let mut second = ranged_ce();
    second.identity.def_name = "RS_SecondRifle".into();
    second.identity.label = "second rifle".into();
    if let Some(r) = second.ranged.as_mut() {
        r.projectile = Some(rimstudio_design::model::ProjectileChoice::Reference(
            "RS_Shot01".into(),
        ));
    }
    let plan = export_plan(&f.ctx, request(&p, &second)).unwrap();
    assert!(!plan.has_errors, "{:?}", plan.diagnostics);
    let file = plan.files.iter().find(|x| x.path == patch_path).unwrap();
    assert_eq!(file.action, FileActionDto::UpdateRegion);
    assert!(file.rendered.contains("RS_NewRifle"));
    assert!(file.rendered.contains("RS_SecondRifle"));
    let removed: Vec<&str> = file
        .diff
        .as_deref()
        .unwrap()
        .lines()
        .filter(|l| l.starts_with('-') && !l.starts_with("---"))
        .collect();
    assert!(removed.is_empty(), "only additions expected: {removed:?}");
    assert!(
        file.rendered
            .starts_with(before.trim_end_matches("</Patch>\n").trim_end())
    );
    assert_gated(&plan);
}
