import { CodeView, DiffView } from 'rimstudio-ui';
import { Section } from '../Section';

const XML = `<?xml version="1.0" encoding="utf-8"?>
<Defs>
  <!-- generated by RimStudio -->
  <ThingDef ParentName="BaseHumanMakeableGun">
    <defName>Gun_PlasmaCarbine</defName>
    <label>plasma carbine</label>
    <statBases>
      <Mass>3.4</Mass>
      <MarketValue>780</MarketValue>
    </statBases>
    <verbs>
      <li>
        <verbClass>Verb_Shoot</verbClass>
        <range>27.9</range>
        <warmupTime desc="aim time">1.1</warmupTime>
      </li>
    </verbs>
  </ThingDef>
</Defs>`;

const DIFF = `--- a/Defs/Gun_PlasmaCarbine.xml
+++ b/Defs/Gun_PlasmaCarbine.xml
@@ -5,6 +5,7 @@
     <label>plasma carbine</label>
     <statBases>
-      <Mass>3.0</Mass>
+      <Mass>3.4</Mass>
+      <MarketValue>780</MarketValue>
     </statBases>
     <verbs>
       <li>
`;

/** Code and diff views. */
export function CodeSection() {
  return (
    <Section id="code" title="Code and diff">
      <div class="max-w-3xl">
        <CodeView label="Definition preview" code={XML} heightClass="max-h-72" />
      </div>
      <div class="max-w-3xl">
        <DiffView label="Changes to Gun_PlasmaCarbine.xml" diff={DIFF} />
      </div>
    </Section>
  );
}
