//! The automatic Combat Extended conversion of an existing mod's weapons (flow D).
//!
//! [`convert_scan`] (the body of the `designer_convert_scan` job) lists the weapon definitions of the open
//! project with a status and the questions the automatic mode cannot answer itself; [`convert_plan`] turns
//! one definition and the user's answers into a write plan. The conversion only ever produces patch files in
//! the gated Combat Extended folder plus the `LoadFolders.xml` edit; the existing definition is the twin and
//! is never changed (D-085). A definition that already carries a conversion gets update mode: per field
//! operations in a RimStudio owned override file, never a second gun conversion.
//!
//! The project is read through a workspace session that has the project folder as its last pack
//! ([`Ctx::project_session`]), so the resolved definitions include the project's own patches (a definition
//! converted by the project's own Combat Extended patch is detected as converted). The raw definition nodes
//! (the ones a patch operation addresses) are read from the project's definition files with `rimstudio-xml`.

use std::collections::BTreeMap;

use rimstudio_core::diag::{DiagCode, Diagnostic, Severity};
use rimstudio_core::jobs::{CancelToken, Progress, ProgressSink, ProgressUnit};
use rimstudio_core::tree::Node;
use rimstudio_design::ce::ammo::ammo_plan;
use rimstudio_design::ce::patchgen::{
    AskItem, AskKind, AskList, CeProjectState, ConversionSource, ConvertAnswers, ConvertCandidate,
    ConvertEnv, ConvertOutcome, ConvertStatus, ValueOrigin, convert, scan,
};
use rimstudio_design::plan::{PlanBuilder, WritePlan};
use rimstudio_ipc_types::designer::{
    AskItemDto, AskKindDto, ConvertAnswerGroupDto, ConvertAnswersDto, ConvertCandidateDto,
    ConvertCountsDto, ConvertRequestDto, ConvertScanDto, ConvertStatusDto,
    DesignerConvertScanRequest,
};
use rimstudio_ipc_types::diagnostic::diagnostics_to_dtos;
use rimstudio_workspace::project::ProjectRecord;
use rimstudio_workspace::refset::PackKind;
use rimstudio_workspace::session::WorkspaceSession;
use rimstudio_workspace::snapshot::DefRef;
use rimstudio_xml::modes::ParseMode;
use rimstudio_xml::reader::parse_top_level;
use serde_json::Value;

use super::convert_facts::facts_of;
use super::ctx::{Ctx, Engine};
use super::dto::kind_to_dto;
use super::plan::{CONVERT_ASK, CONVERT_DERIVED, finish_ce};
use crate::error::{ToolkitError, ToolkitResult};
use crate::shared::projectfs::ProjectView;

/// The marker the generator writes into the comment of every file it owns.
const OWNED_MARK: &str = "generated by RimStudio";

/// The definitions of the project's own files: the raw nodes and the file each one is in.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProjectDefs {
    /// The raw top level nodes of every definition file of the project, in file order.
    pub nodes: Vec<Node>,
    /// The project file (relative to the project root) of each definition, by def name.
    pub files: BTreeMap<String, String>,
    /// Definition files that could not be read, with the reason.
    pub unreadable: Vec<(String, String)>,
}

/// The result of planning one conversion.
#[derive(Debug, Clone, PartialEq)]
pub struct ConvertPlanResult {
    /// The plan: the patch file and `LoadFolders.xml`. Empty while questions are open.
    pub plan: WritePlan,
    /// The diagnostics of the plan, the open questions (as errors with the field pointer) and the lint.
    pub diagnostics: Vec<Diagnostic>,
    /// What is still to ask.
    pub asks: AskList,
    /// True when the target already carried a conversion and update mode was used.
    pub update: bool,
    /// The raw project definitions a dry apply of the patch runs against.
    pub scratch_defs: Vec<Node>,
}

/// Reads the raw definition nodes of the project's definition files from a session whose last pack is the
/// project.
#[must_use]
pub fn project_defs(session: &WorkspaceSession, view: &ProjectView) -> ProjectDefs {
    let mut out = ProjectDefs::default();
    let packs = &session.reference().packs;
    let Some(pack_index) = packs.iter().rposition(|p| p.kind == PackKind::Project) else {
        return out;
    };
    let mut files: Vec<&rimstudio_workspace::session::FileEntry> = session
        .files()
        .iter()
        .filter(|f| f.pack == pack_index && f.kind == rimstudio_workspace::parse::FileKind::Defs)
        .collect();
    files.sort_by(|a, b| a.path.cmp(&b.path));
    for entry in files {
        let rel = entry.path.strip_prefix(&view.root).map_or_else(
            |_| entry.relative.clone(),
            |p| p.as_str().replace('\\', "/"),
        );
        let bytes = match std::fs::read(entry.path.as_std_path()) {
            Ok(b) => b,
            Err(e) => {
                out.unreadable.push((rel, e.to_string()));
                continue;
            }
        };
        match parse_top_level(&bytes, ParseMode::Tolerant, "Defs") {
            Ok(parsed) => {
                for node in parsed.nodes {
                    let name = node
                        .child_text("defName")
                        .map(str::to_owned)
                        .or_else(|| node.attr("Name").map(str::to_owned));
                    if let Some(name) = name {
                        out.files.entry(name).or_insert_with(|| rel.clone());
                    }
                    out.nodes.push(node);
                }
            }
            Err(e) => out.unreadable.push((rel, e.to_string())),
        }
    }
    out
}

/// Where the existing conversion of a def came from, read from its provenance in the project session.
///
/// The last patch that converts the def (the gun conversion operation, else the last patch that touched it)
/// decides: a patch of the project is RimStudio owned when its file carries the generator's comment, else
/// project owned; a patch of another mod is foreign. A def converted inside its own definition is a project
/// conversion.
fn conversion_source(
    session: &WorkspaceSession,
    view: &ProjectView,
    engine: &Engine,
    def_name: &str,
) -> ConversionSource {
    let snapshot = session.current();
    let Some(resolved) = snapshot.resolve_def(&DefRef::new("ThingDef", def_name)) else {
        return ConversionSource::Unknown;
    };
    let provenance = resolved.provenance;
    let make_gun = &engine.ce().classes.make_gun_op;
    let patch = provenance
        .patched_by
        .iter()
        .rev()
        .find(|p| p.class == *make_gun)
        .or_else(|| provenance.patched_by.last());
    let classify = |kind: Option<PackKind>, name: &str, path: Option<&camino::Utf8Path>| match kind
    {
        Some(PackKind::Project) => {
            let rel = path.map(|p| {
                p.strip_prefix(&view.root)
                    .map_or_else(|_| p.to_string(), |r| r.as_str().replace('\\', "/"))
            });
            let owned = path
                .and_then(|p| std::fs::read_to_string(p.as_std_path()).ok())
                .is_some_and(|t| t.contains(OWNED_MARK));
            if owned {
                ConversionSource::RimStudio(rel)
            } else {
                ConversionSource::Project(rel)
            }
        }
        Some(_) => ConversionSource::Foreign(Some(name.to_owned())),
        None => ConversionSource::Unknown,
    };
    match patch {
        Some(p) => classify(
            p.pack.as_ref().map(|r| r.kind),
            p.pack.as_ref().map_or("", |r| r.name.as_str()),
            p.file.as_ref().map(|f| f.path.as_path()),
        ),
        None => classify(
            provenance.pack.as_ref().map(|r| r.kind),
            provenance.pack.as_ref().map_or("", |r| r.name.as_str()),
            provenance.file.as_ref().map(|f| f.path.as_path()),
        ),
    }
}

/// Merges `from` into `into`: objects merge member by member, everything else (lists included) is replaced.
fn merge_json(into: &mut Value, from: &Value) {
    match (into, from) {
        (Value::Object(a), Value::Object(b)) => {
            for (k, v) in b {
                match a.get_mut(k) {
                    Some(slot) => merge_json(slot, v),
                    None => {
                        a.insert(k.clone(), v.clone());
                    }
                }
            }
        }
        (slot, v) => *slot = v.clone(),
    }
}

/// The answers of the request itself as a JSON object holding only what the user set.
///
/// The two flags of the override block (`oneHanded`, `beltFed`) are plain booleans in the DTO and always
/// serialised; `false` there means "not set" and is dropped, so that it cannot hide a group's `true`.
fn own_answers_value(dto: &ConvertAnswersDto) -> ToolkitResult<Value> {
    let mut value = serde_json::to_value(dto)
        .map_err(|e| ToolkitError::internal(format!("the answers cannot be encoded: {e}")))?;
    if let Some(Value::Object(overrides)) = value.get_mut("overrides") {
        for flag in ["oneHanded", "beltFed"] {
            if overrides.get(flag) == Some(&Value::Bool(false)) {
                overrides.remove(flag);
            }
        }
        if overrides.is_empty()
            && let Some(map) = value.as_object_mut()
        {
            map.remove("overrides");
        }
    }
    Ok(value)
}

/// True when the group applies to the definition: it names the definition, or its family key is the
/// definition's, or it names neither (the defaults of an answers file).
#[must_use]
pub fn group_applies(group: &ConvertAnswerGroupDto, def_name: &str, family: &str) -> bool {
    let unrestricted = group.family.is_none() && group.def_names.is_empty();
    unrestricted
        || group.def_names.iter().any(|d| d == def_name)
        || group
            .family
            .as_deref()
            .is_some_and(|f| !family.is_empty() && f == family)
}

/// The answers of one definition: the groups that apply to it in order, then the request's own answers on
/// top (member by member, the later one wins).
///
/// # Errors
///
/// [`ToolkitError::InvalidDraft`] for a group whose answers are not an object or for answers that do not fit
/// the answer shape.
pub fn answers_for_def(request: &ConvertRequestDto, family: &str) -> ToolkitResult<ConvertAnswers> {
    let mut merged = Value::Object(serde_json::Map::new());
    for (i, group) in request.groups.iter().enumerate() {
        if !group_applies(group, &request.def_name, family) {
            continue;
        }
        if !group.answers.is_object() {
            return Err(ToolkitError::invalid_draft(format!(
                "answer group {} must be an object of answers",
                i + 1
            )));
        }
        merge_json(&mut merged, &group.answers);
    }
    merge_json(&mut merged, &own_answers_value(&request.answers)?);
    serde_json::from_value(merged)
        .map_err(|e| ToolkitError::invalid_draft(format!("the answers do not fit: {e}")))
}

fn ask_dto(item: &AskItem) -> AskItemDto {
    AskItemDto {
        field: item.field.clone(),
        label: item.label.clone(),
        kind: match item.kind {
            AskKind::Choice => AskKindDto::Choice,
            AskKind::Flag => AskKindDto::Flag,
            AskKind::Number => AskKindDto::Number,
        },
        options: item.options.clone(),
        reason: item.reason.clone(),
        suggestion: item.suggestion,
    }
}

/// The text of an open question in a plan: the label, then why it is asked and the rejected estimate.
///
/// The reason of the engine already names the estimate and its rating, so the text is the label followed
/// by the reason; a bare suggestion without a reason is shown as such.
fn ask_message(item: &AskItem) -> String {
    match (&item.reason, item.suggestion) {
        (Some(reason), _) => format!("{} (asked because {reason})", item.label),
        (None, Some(s)) => format!("{} (rejected estimate {s})", item.label),
        (None, None) => item.label.clone(),
    }
}

fn status_dto(status: ConvertStatus) -> ConvertStatusDto {
    match status {
        ConvertStatus::NotConverted => ConvertStatusDto::NotConverted,
        ConvertStatus::AlreadyCe => ConvertStatusDto::AlreadyCe,
        ConvertStatus::UnsupportedKind => ConvertStatusDto::UnsupportedKind,
        ConvertStatus::TargetNotFound => ConvertStatusDto::TargetNotFound,
    }
}

/// What a conversion call works on: the session, the engine and the project definitions.
struct Work<'a> {
    engine: &'a Engine,
    session: &'a WorkspaceSession,
    view: &'a ProjectView,
    defs: ProjectDefs,
    state: CeProjectState,
}

fn work<'a>(
    ctx: &Ctx,
    engine: &'a Engine,
    session: &'a WorkspaceSession,
    view: &'a ProjectView,
) -> Work<'a> {
    let fallback = ctx
        .session()
        .map(|s| {
            let v = &s.reference().game_version;
            format!("{}.{}", v.major, v.minor)
        })
        .unwrap_or_else(|| "1.6".to_owned());
    Work {
        engine,
        session,
        view,
        defs: project_defs(session, view),
        state: CeProjectState {
            load_folders: view.load_folders.as_ref().map(|f| f.root.clone()),
            supported_versions: view.supported_versions.clone(),
            game_version: view.game_version(&fallback),
            container: None,
        },
    }
}

fn convert_one(
    w: &Work<'_>,
    candidate: &ConvertCandidate,
    answers: &ConvertAnswers,
    snapshot: &rimstudio_workspace::snapshot::Snapshot,
) -> ConvertOutcome {
    let source = conversion_source(w.session, w.view, w.engine, &candidate.def);
    let env = ConvertEnv {
        dbs: &snapshot.databases,
        model: w.engine.ce(),
        layout: &w.view.layout,
        reader: w.engine.reader_options(),
        project: &w.defs.nodes,
        state: &w.state,
        source: &source,
    };
    convert(candidate, answers, &env)
}

fn require_ce(engine: &Engine) -> ToolkitResult<()> {
    if engine.ce_available() {
        Ok(())
    } else {
        Err(ToolkitError::ReferenceUnavailable {
            reason: "no Combat Extended data is loaded, so weapons cannot be converted".to_owned(),
        })
    }
}

/// `designer_convert_scan`: lists the weapon definitions of the project with their conversion status and
/// the questions the automatic mode cannot answer itself. Reads the project, writes nothing.
///
/// # Errors
///
/// [`ToolkitError::ReferenceUnavailable`] without a game install or without Combat Extended data,
/// [`ToolkitError::ProjectNotOpen`] and [`ToolkitError::Cancelled`].
pub fn convert_scan(
    ctx: &Ctx,
    req: DesignerConvertScanRequest,
    progress: &dyn ProgressSink,
    cancel: &CancelToken,
) -> ToolkitResult<ConvertScanDto> {
    let engine = ctx.require_engine()?;
    require_ce(&engine)?;
    let (_record, view) = ctx.env().view(&req.project_id)?;
    cancel.check()?;
    let session = ctx.project_session(&view.root)?;
    let snapshot = session.current();
    let w = work(ctx, &engine, &session, &view);
    let found = scan(&w.defs.nodes, &snapshot.databases, engine.ce());
    let total = found.len() as u64;
    let mut candidates = Vec::new();
    let mut counts = ConvertCountsDto::default();
    let mut diagnostics: Vec<Diagnostic> = view.diagnostics.clone();
    for (path, why) in &w.defs.unreadable {
        diagnostics.push(
            Diagnostic::new(
                DiagCode::new("designer.def-file-unreadable"),
                Severity::Warning,
                format!("{path} could not be read: {why}"),
            )
            .with_arg("path", path),
        );
    }
    for (done, c) in found.iter().enumerate() {
        cancel.check()?;
        progress.report(
            Progress::new("designer.convert-scan", done as u64)
                .with_total(total)
                .with_unit(ProgressUnit::Items),
        );
        match c.status {
            ConvertStatus::NotConverted => counts.not_converted += 1,
            ConvertStatus::AlreadyCe => counts.already_ce += 1,
            ConvertStatus::UnsupportedKind => counts.unsupported_kind += 1,
            ConvertStatus::TargetNotFound => counts.target_not_found += 1,
        }
        if !req.include_converted && c.status == ConvertStatus::AlreadyCe {
            continue;
        }
        let asks = if c.status == ConvertStatus::NotConverted {
            convert_one(&w, c, &ConvertAnswers::default(), &snapshot)
                .asks
                .items
                .iter()
                .map(ask_dto)
                .collect()
        } else {
            Vec::new()
        };
        let facts = facts_of(&snapshot.databases, &c.def);
        candidates.push(ConvertCandidateDto {
            def_name: c.def.clone(),
            label: c.label.clone(),
            kind: c.kind.and_then(|k| kind_to_dto(k).ok()),
            status: status_dto(c.status),
            reason: c.reason.clone(),
            file: w.defs.files.get(&c.def).cloned(),
            asks,
            family: c.family.clone(),
            tags: facts.tags,
            weapon_classes: facts.weapon_classes,
            vanilla: facts.numbers,
        });
    }
    progress.report(
        Progress::new("designer.convert-scan", total)
            .with_total(total)
            .with_unit(ProgressUnit::Items),
    );
    candidates.sort_by(|a, b| a.def_name.cmp(&b.def_name));
    Ok(ConvertScanDto {
        candidates,
        counts,
        diagnostics: diagnostics_to_dtos(&diagnostics),
    })
}

/// Plans the conversion of one definition of the project. The plan holds patch files and `LoadFolders.xml`
/// only. Open questions give an empty plan and one error diagnostic per question (the field pointer is the
/// `field` argument); a definition that is not convertible gives an error diagnostic.
///
/// # Errors
///
/// [`ToolkitError::ReferenceUnavailable`] without Combat Extended data, [`ToolkitError::InvalidDraft`] for
/// answers that do not fit.
pub fn convert_plan(
    ctx: &Ctx,
    _record: &ProjectRecord,
    view: &ProjectView,
    request: &ConvertRequestDto,
) -> ToolkitResult<ConvertPlanResult> {
    let engine = ctx.require_engine()?;
    require_ce(&engine)?;
    let session = ctx.project_session(&view.root)?;
    let snapshot = session.current();
    let w = work(ctx, &engine, &session, view);
    let found = scan(&w.defs.nodes, &snapshot.databases, engine.ce());
    let Some(candidate) = found.iter().find(|c| c.def == request.def_name) else {
        return Ok(ConvertPlanResult {
            plan: WritePlan::default(),
            diagnostics: vec![
                Diagnostic::new(
                    DiagCode::new("designer.convert-unknown-def"),
                    Severity::Error,
                    format!(
                        "{} is not a weapon definition of the project",
                        request.def_name
                    ),
                )
                .with_arg("field", "/convert/defName"),
            ],
            asks: AskList::default(),
            update: false,
            scratch_defs: Vec::new(),
        });
    };
    let answers = answers_for_def(request, &candidate.family)?;
    let outcome = convert_one(&w, candidate, &answers, &snapshot);
    let mut diagnostics: Vec<Diagnostic> = Vec::new();
    for ask in &outcome.asks.items {
        diagnostics.push(
            Diagnostic::new(CONVERT_ASK, Severity::Error, ask_message(ask))
                .with_arg("field", ask.field.clone()),
        );
    }
    for d in &outcome.derived {
        let how = match &d.origin {
            ValueOrigin::Vanilla => "copied from the vanilla definition".to_owned(),
            ValueOrigin::Predicted { predictor, n } => {
                format!("predicted ({predictor:?}) from {n} of your converted weapons; check it")
            }
        };
        diagnostics.push(
            Diagnostic::new(
                CONVERT_DERIVED,
                Severity::Info,
                format!("{} = {} was {how}", d.field, d.value),
            )
            .with_arg("field", d.field.clone()),
        );
    }
    // open questions end the conversion before the ammunition is looked at; its own checks still run, so
    // the custom ammo window can show them while the other questions are being answered
    if !outcome.asks.items.is_empty()
        && let Some(spec) = outcome
            .spec
            .as_ref()
            .filter(|s| s.ce.as_ref().is_some_and(|c| c.custom_ammo.is_some()))
    {
        diagnostics.extend(ammo_plan(spec, engine.ce(), &view.layout).diagnostics);
    }
    let mut builder = PlanBuilder::new();
    let mut known: std::collections::BTreeSet<String> = w
        .defs
        .nodes
        .iter()
        .filter_map(|n| n.child_text("defName").map(str::to_owned))
        .collect();
    // the defs of a custom caliber are written by the plan, so the lint may treat them as defined
    if let Some(spec) = &outcome.spec {
        known.extend(super::ammo::custom_known_defs(spec));
    }
    diagnostics.extend(finish_ce(
        &engine,
        view,
        &w.state,
        outcome.plan,
        &known,
        &mut builder,
    ));
    Ok(ConvertPlanResult {
        plan: builder.build(),
        diagnostics,
        asks: outcome.asks,
        update: outcome.update,
        scratch_defs: w.defs.nodes,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use rimstudio_ipc_types::designer::ConvertRequestDto;
    use serde_json::json;

    fn item(reason: Option<&str>, suggestion: Option<f64>) -> AskItem {
        AskItem {
            field: "/ce/shotSpread".into(),
            label: "Shot spread".into(),
            kind: AskKind::Number,
            options: Vec::new(),
            reason: reason.map(str::to_owned),
            suggestion,
        }
    }

    #[test]
    fn the_ask_dto_carries_the_reason_and_the_rejected_estimate() {
        let dto = ask_dto(&item(Some("rated unreliable"), Some(1.25)));
        assert_eq!(dto.reason.as_deref(), Some("rated unreliable"));
        assert_eq!(dto.suggestion, Some(1.25));
        let plain = ask_dto(&item(None, None));
        assert!(plain.reason.is_none() && plain.suggestion.is_none());
    }

    #[test]
    fn the_plan_message_of_an_ask_names_the_reason_or_the_bare_estimate() {
        assert_eq!(ask_message(&item(None, None)), "Shot spread");
        assert_eq!(
            ask_message(&item(Some("it is unreliable"), Some(1.25))),
            "Shot spread (asked because it is unreliable)"
        );
        assert_eq!(
            ask_message(&item(None, Some(1.25))),
            "Shot spread (rejected estimate 1.25)"
        );
    }

    fn request(
        def: &str,
        own: ConvertAnswersDto,
        groups: Vec<ConvertAnswerGroupDto>,
    ) -> ConvertRequestDto {
        ConvertRequestDto {
            def_name: def.into(),
            answers: own,
            groups,
        }
    }

    fn group(family: Option<&str>, defs: &[&str], answers: Value) -> ConvertAnswerGroupDto {
        ConvertAnswerGroupDto {
            family: family.map(str::to_owned),
            def_names: defs.iter().map(|d| (*d).to_owned()).collect(),
            answers,
        }
    }

    #[test]
    fn a_family_group_applies_to_the_family_and_a_definition_group_to_its_names() {
        let by_family = group(Some("ranged/RS_Tag/RS_Shot"), &[], json!({}));
        assert!(group_applies(&by_family, "RS_A", "ranged/RS_Tag/RS_Shot"));
        assert!(!group_applies(&by_family, "RS_A", "ranged/RS_Tag/RS_Other"));
        assert!(!group_applies(&by_family, "RS_A", ""));
        let by_name = group(None, &["RS_A", "RS_B"], json!({}));
        assert!(group_applies(&by_name, "RS_B", "anything"));
        assert!(!group_applies(&by_name, "RS_C", "anything"));
        let everyone = group(None, &[], json!({}));
        assert!(group_applies(&everyone, "RS_C", ""));
    }

    #[test]
    fn groups_apply_in_order_and_the_own_answers_win_member_by_member() {
        let groups = vec![
            group(
                None,
                &[],
                json!({"ammoSet": "RS_Default", "oneHanded": true,
                       "overrides": {"bulk": {"value": 1.0}, "swayFactor": {"value": 2.0}}}),
            ),
            group(
                Some("fam"),
                &[],
                json!({"ammoSet": "RS_Family", "overrides": {"bulk": {"value": 3.0}}}),
            ),
        ];
        let own = ConvertAnswersDto {
            weapon_tag_class: Some("RS_Own".into()),
            ..ConvertAnswersDto::default()
        };
        let a = answers_for_def(&request("RS_A", own, groups.clone()), "fam").unwrap();
        assert_eq!(a.ammo_set.as_deref(), Some("RS_Family"));
        assert_eq!(a.weapon_tag_class.as_deref(), Some("RS_Own"));
        assert_eq!(a.one_handed, Some(true));
        let value = serde_json::to_value(&a).unwrap();
        assert_eq!(value["overrides"]["bulk"]["value"], json!(3.0));
        assert_eq!(value["overrides"]["swayFactor"]["value"], json!(2.0));
        // another family only gets the defaults
        let b = answers_for_def(
            &request("RS_B", ConvertAnswersDto::default(), groups),
            "other",
        )
        .unwrap();
        assert_eq!(b.ammo_set.as_deref(), Some("RS_Default"));
    }

    #[test]
    fn an_unset_flag_of_the_request_does_not_hide_a_group_flag() {
        let groups = vec![group(
            None,
            &[],
            json!({"overrides": {"beltFed": true, "oneHanded": true}}),
        )];
        let a =
            answers_for_def(&request("RS_A", ConvertAnswersDto::default(), groups), "").unwrap();
        let value = serde_json::to_value(&a).unwrap();
        assert_eq!(value["overrides"]["beltFed"], json!(true));
        assert_eq!(value["overrides"]["oneHanded"], json!(true));
    }

    #[test]
    fn a_group_that_is_not_an_object_is_refused() {
        let groups = vec![group(None, &[], json!("ammoSet"))];
        let err = answers_for_def(&request("RS_A", ConvertAnswersDto::default(), groups), "")
            .unwrap_err();
        assert_eq!(err.code(), "designer.invalid-draft");
    }

    #[test]
    fn no_groups_gives_exactly_the_own_answers() {
        let own = ConvertAnswersDto {
            ammo_set: Some("RS_Set".into()),
            belt_fed: Some(false),
            ..ConvertAnswersDto::default()
        };
        let a = answers_for_def(&request("RS_A", own, Vec::new()), "").unwrap();
        assert_eq!(a.ammo_set.as_deref(), Some("RS_Set"));
        assert_eq!(a.belt_fed, Some(false));
    }
}
