//! The Combat Extended write plan: the patch file and the `LoadFolders.xml` edit.
//!
//! [`export_ce_plan`] is the counterpart of [`crate::plan::export_vanilla_plan`]. It produces only files of
//! the CE folder (kind [`FileKind::CePatch`]) and `LoadFolders.xml`; the vanilla definition file is never in
//! it. The toolkit merges the two plans when the user opted in. Nothing is produced when the spec has no
//! Combat Extended block (CP-020).
//!
//! The gate test [`gate_violations`] checks the rule of IT-052 over any plan: a file that holds a Combat
//! Extended class must be a patch file under the gated CE folder.

use rimstudio_core::diag::Diagnostic;
use rimstudio_core::tree::Node;

use super::container::Container;
use super::folders::load_folders_plan;
use super::{GeneratedPatch, PatchMode, gun_patch, melee_patch};
use crate::ce::lint::codes::{ABOUT_SUGGESTION, CEP004, DERIVED_FAR, DERIVED_VALUE};
use crate::ce::reader::CeModel;
use crate::model::{DesignSpec, ItemKind};
use crate::plan::{
    FileKind, PlanBuilder, PlannedFile, ProjectLayout, SectionHeader, WritePlan,
    is_safe_relative_path,
};
use crate::validation::{codes::CE_ABSENT, has_errors};

/// The text that marks a Combat Extended class: the namespace with its dot, so a package id such as
/// `CETeam.CombatExtended` in an `IfModActive` attribute of an existing `LoadFolders.xml` does not count.
/// The text that marks a Combat Extended class (a namespace prefix, so a package id does not match).
pub const CE_MARK: &str = "CombatExtended.";

/// What the planner needs to know about the project beyond the spec.
#[derive(Debug, Clone, PartialEq)]
pub struct CeProjectState {
    /// The parsed `LoadFolders.xml` of the project, `None` when it has none.
    pub load_folders: Option<Node>,
    /// The `supportedVersions` of the mod's About file (for the suggestion to add the game version).
    pub supported_versions: Vec<String>,
    /// The game version whose block is served, `1.6` by default.
    pub game_version: String,
    /// The state of the target def. `None` builds it from the vanilla definition of the spec (a new item).
    pub container: Option<Container>,
}

impl Default for CeProjectState {
    fn default() -> Self {
        Self {
            load_folders: None,
            supported_versions: Vec::new(),
            game_version: "1.6".to_owned(),
            container: None,
        }
    }
}

/// The folder (relative to the project root) that holds the CE patch files of a layout.
#[must_use]
pub fn ce_dir(layout: &ProjectLayout) -> String {
    layout.in_version(&layout.ce_folder)
}

/// The files of a plan that break the gating rule: they contain a Combat Extended class and are not a patch
/// file below the gated CE folder of the layout.
#[must_use]
pub fn gate_violations(plan: &WritePlan, layout: &ProjectLayout) -> Vec<String> {
    let dir = format!("{}/", ce_dir(layout));
    plan.files
        .iter()
        .filter(|f| f.contains_text(CE_MARK))
        .filter(|f| !(f.kind == FileKind::CePatch && f.path.starts_with(&dir)))
        .map(|f| f.path.clone())
        .collect()
}

fn error_plan(diagnostics: Vec<Diagnostic>) -> WritePlan {
    let mut builder = PlanBuilder::new();
    builder.extend_diagnostics(diagnostics);
    builder.build()
}

/// The patch file of a generated patch: a `Patch` tree with one section header naming the def and marking
/// the file as RimStudio output.
fn patch_file(patch: &GeneratedPatch, layout: &ProjectLayout) -> PlannedFile {
    let stem = match patch.mode {
        PatchMode::Update => format!("{}_Update", patch.category.file_stem()),
        _ => patch.category.file_stem().to_owned(),
    };
    PlannedFile::new_file(
        layout.ce_patch_path(&stem),
        FileKind::CePatch,
        patch.patch_root(),
        vec![SectionHeader {
            first_child: 0,
            comment: format!(
                "====== {def} ====== generated by RimStudio, draft {def}",
                def = patch.def_name
            ),
        }],
    )
}

/// Plausibility window of a predicted number against the vanilla number it replaces (an implementation
/// choice, not a game value): outside it the plan carries a warning.
const FAR_RATIO_MIN: f64 = 0.6;
/// Upper end of the plausibility window.
const FAR_RATIO_MAX: f64 = 2.5;

/// The vanilla number of the spec when the predicted `value` of `field` (range or mass) lies outside the
/// plausibility window around it.
fn far_from_vanilla(spec: &DesignSpec, field: &str, value: f64) -> Option<f64> {
    let vanilla = match field {
        "range" => spec.ranged.as_ref().and_then(|r| r.range).map(|v| v.value),
        "mass" => spec.mass.map(|v| v.value),
        _ => None,
    }?;
    if !(vanilla > 0.0 && value.is_finite()) {
        return None;
    }
    let ratio = value / vanilla;
    (!(FAR_RATIO_MIN..=FAR_RATIO_MAX).contains(&ratio)).then_some(vanilla)
}

/// Builds the CE write plan of a spec with the default project state (no `LoadFolders.xml` yet, game version
/// 1.6, the target is the vanilla definition of the spec). See [`export_ce_plan_with`].
#[must_use]
pub fn export_ce_plan(spec: &DesignSpec, model: &CeModel, layout: &ProjectLayout) -> WritePlan {
    export_ce_plan_with(spec, model, layout, &CeProjectState::default())
}

/// Builds the CE write plan of a spec.
///
/// - No Combat Extended block in the spec: an empty plan without diagnostics (the toggle is off).
/// - No Combat Extended in the model: an empty plan with `design.ce-absent`.
/// - An error in the spec or the layout: no files, the diagnostics only.
/// - Otherwise: the patch file `[<version>/]<ce folder>/Patches/[<slug>_]Weapons_<Kind>.xml` (with
///   `_Update` in the name for an already converted target) and `LoadFolders.xml` (unless it already holds
///   the gate). A last guard checks the gating rule over the finished plan.
#[must_use]
pub fn export_ce_plan_with(
    spec: &DesignSpec,
    model: &CeModel,
    layout: &ProjectLayout,
    state: &CeProjectState,
) -> WritePlan {
    if spec.ce.is_none() {
        return WritePlan::default();
    }
    if !model.is_present() {
        return error_plan(vec![CE_ABSENT.diagnostic("", &[])]);
    }
    let layout_problems = layout.validate();
    if has_errors(&layout_problems) {
        return error_plan(layout_problems);
    }
    let container = state
        .container
        .clone()
        .unwrap_or_else(|| Container::from_spec(spec));
    let generated = match spec.kind {
        ItemKind::Ranged => gun_patch(spec, model, &container),
        ItemKind::Melee => melee_patch(spec, model, &container),
    };
    let patch = match generated {
        Ok(p) => p,
        Err(e) => {
            return error_plan(vec![Diagnostic::new(
                rimstudio_core::diag::DiagCode::new(e.code()),
                rimstudio_core::diag::Severity::Error,
                e.to_string(),
            )]);
        }
    };
    let mut diagnostics = layout_problems;
    diagnostics.extend(patch.diagnostics.iter().cloned());
    for d in &patch.derived {
        let error = d
            .error
            .map(|e| format!(", typical error about {:.0} percent", 100.0 * e))
            .unwrap_or_default();
        let rating = d.rating.map_or("", |r| r.label());
        let how = match (&d.origin, d.rating) {
            (super::ValueOrigin::Vanilla, Some(r)) if !r.is_usable() => format!(
                "copied from the vanilla definition: the estimate from the converted weapons in the library was rated {rating}{error} and is not used"
            ),
            (super::ValueOrigin::Vanilla, _) => "copied from the vanilla definition".to_owned(),
            (super::ValueOrigin::Predicted { predictor, n }, _) => format!(
                "predicted ({predictor:?}) from {n} of the converted weapons in the library, rated {rating}{error}; check it"
            ),
        };
        diagnostics.push(DERIVED_VALUE.diagnostic(
            &d.field,
            &[
                ("field", d.field.as_str()),
                ("value", &d.value.to_string()),
                ("how", &how),
            ],
        ));
    }
    for d in &patch.derived {
        if matches!(d.origin, super::ValueOrigin::Predicted { .. })
            && let Some(vanilla) = far_from_vanilla(spec, &d.field, d.value)
        {
            diagnostics.push(DERIVED_FAR.diagnostic(
                &d.field,
                &[
                    ("field", d.field.as_str()),
                    ("value", &d.value.to_string()),
                    ("vanilla", &vanilla.to_string()),
                ],
            ));
        }
    }
    if has_errors(&diagnostics) || patch.operations.is_empty() {
        return error_plan(diagnostics);
    }
    let package_id = super::ce_package_id(model);
    let package_id = package_id.as_str();
    let folders = load_folders_plan(
        state.load_folders.as_ref(),
        layout,
        &state.game_version,
        package_id,
    );
    diagnostics.extend(folders.diagnostics);
    if !state.supported_versions.is_empty()
        && !state
            .supported_versions
            .iter()
            .any(|v| v == &state.game_version)
    {
        diagnostics.push(ABOUT_SUGGESTION.diagnostic(
            "",
            &[(
                "suggestion",
                &format!("add {} to supportedVersions", state.game_version),
            )],
        ));
    }
    diagnostics.push(ABOUT_SUGGESTION.diagnostic(
        "",
        &[(
            "suggestion",
            &format!("add loadAfter {package_id} (Combat Extended)"),
        )],
    ));
    let mut builder = PlanBuilder::new();
    let file = patch_file(&patch, layout);
    if !is_safe_relative_path(&file.path) {
        return error_plan(diagnostics);
    }
    builder.add_file(file);
    if let Some(f) = folders.file {
        builder.add_file(f);
    }
    builder.extend_diagnostics(diagnostics);
    let plan = builder.build();
    let violations = gate_violations(&plan, layout);
    if violations.is_empty() {
        plan
    } else {
        error_plan(
            violations
                .iter()
                .map(|path| {
                    CEP004
                        .diagnostic("", &[("class", CE_MARK)])
                        .with_arg("path", path)
                })
                .collect(),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plan::{FileAction, PlannedFile};
    use rimstudio_core::tree::Node;

    #[test]
    fn gate_violations_name_files_outside_the_ce_folder() {
        let layout = ProjectLayout::default();
        let mut ce_tree = Node::new("Patch");
        ce_tree.set_attr("Class", "CombatExtended.X");
        let inside = PlannedFile::new_file(
            "Compat/CombatExtended/Patches/A.xml",
            FileKind::CePatch,
            ce_tree.clone(),
            vec![],
        );
        let outside =
            PlannedFile::new_file("Patches/A.xml", FileKind::CePatch, ce_tree.clone(), vec![]);
        let vanilla = PlannedFile::new_file("Defs/A.xml", FileKind::VanillaDefs, ce_tree, vec![]);
        let plan = WritePlan {
            files: vec![inside, outside, vanilla],
            diagnostics: vec![],
        };
        assert_eq!(
            gate_violations(&plan, &layout),
            ["Patches/A.xml", "Defs/A.xml"]
        );
        assert_eq!(plan.files[0].action, FileAction::Create);
    }

    #[test]
    fn the_ce_dir_follows_the_version_folder() {
        assert_eq!(ce_dir(&ProjectLayout::default()), "Compat/CombatExtended");
        assert_eq!(
            ce_dir(&ProjectLayout::with_version_folder("1.6")),
            "1.6/Compat/CombatExtended"
        );
    }
}

#[cfg(test)]
mod far_tests {
    use super::*;
    use crate::model::{RangedInputs, Sourced};

    fn spec(range: f64, mass: f64) -> DesignSpec {
        let mut s = DesignSpec::new_ranged("RS_Far", "far");
        s.mass = Some(Sourced::typed(mass));
        s.ranged = Some(RangedInputs {
            range: Some(Sourced::typed(range)),
            ..RangedInputs::default()
        });
        s
    }

    #[test]
    fn a_predicted_range_far_below_or_above_the_vanilla_range_is_flagged() {
        assert_eq!(
            far_from_vanilla(&spec(44.0, 3.0), "range", 16.0),
            Some(44.0)
        );
        assert_eq!(
            far_from_vanilla(&spec(10.0, 3.0), "range", 40.0),
            Some(10.0)
        );
    }

    #[test]
    fn plausible_predictions_other_fields_and_missing_numbers_are_not_flagged() {
        assert_eq!(far_from_vanilla(&spec(44.0, 3.0), "range", 55.0), None);
        assert_eq!(far_from_vanilla(&spec(44.0, 3.0), "range", 44.0), None);
        assert_eq!(far_from_vanilla(&spec(44.0, 3.0), "warmup", 0.1), None);
        assert_eq!(far_from_vanilla(&spec(0.0, 3.0), "range", 10.0), None);
        assert_eq!(far_from_vanilla(&spec(44.0, 3.0), "range", f64::NAN), None);
        let mut no_range = spec(44.0, 3.0);
        no_range.ranged = None;
        assert_eq!(far_from_vanilla(&no_range, "range", 1.0), None);
    }

    #[test]
    fn a_predicted_mass_far_from_the_vanilla_mass_is_flagged() {
        assert_eq!(far_from_vanilla(&spec(44.0, 3.0), "mass", 9.0), Some(3.0));
    }
}
