//! Generates the TypeScript bindings of the webview and checks that the committed copies are current.
//!
//! Two files are produced in `packages/ipc-types/src`:
//!
//! - `bindings.ts`: every DTO type reachable from the command table, plus the extra roots listed in
//!   [`extra_roots`], as one deterministic file of `export type` declarations;
//! - `commands.ts`: a typed table of the registry rows (camelCase export name, snake_case command name,
//!   kind, request and response types) with the helper types `CommandName`, `CommandRequest<N>` and
//!   `CommandResponse<N>`.
//!
//! By default the test compares the output with the committed files and fails when they differ.
//! Refresh them with `UPDATE_BINDINGS=1 cargo test -p rimstudio-app --test bindings`.

#![allow(clippy::expect_used, clippy::unwrap_used)]

use std::any::TypeId;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::PathBuf;

use rimstudio_app::for_each_command;
use rimstudio_app::registry::wire::*;
use rimstudio_ipc_types::designer::{DesignerMaterialMatrixRequest, MaterialMatrixDto};
use rimstudio_ipc_types::error::ApiError;
use rimstudio_ipc_types::jobs::{JobEvent, JobHandleDto, JobResultEnvelope, ProgressDto};
use rimstudio_ipc_types::mods::ModsSnapshot;
use serde_json::Value;
use ts_rs::{Config, TS, TypeVisitor};

const REFRESH: &str = "UPDATE_BINDINGS=1 cargo test -p rimstudio-app --test bindings";

/// Collects the declaration of a type and of everything it mentions.
struct Collector {
    cfg: Config,
    visited: BTreeSet<TypeIdKey>,
    decls: BTreeMap<String, String>,
}

/// `TypeId` has no `Ord` guarantee across versions that we want to lean on, so keep its debug text.
type TypeIdKey = String;

impl Collector {
    fn new() -> Self {
        Self {
            cfg: Config::new().with_large_int("number"),
            visited: BTreeSet::new(),
            decls: BTreeMap::new(),
        }
    }

    fn add<T: TS + 'static + ?Sized>(&mut self) {
        let key = format!("{:?}", TypeId::of::<T>());
        if !self.visited.insert(key) {
            return;
        }
        if T::output_path().is_some() {
            let ident = T::ident(&self.cfg);
            let decl = T::decl(&self.cfg);
            let docs = T::docs()
                .map(|d| format!("{}\n", d.trim_end()))
                .unwrap_or_default();
            let text = format!("{docs}export {decl}");
            if let Some(previous) = self.decls.get(&ident) {
                assert_eq!(
                    previous, &text,
                    "two different types are both named {ident}"
                );
            } else {
                self.decls.insert(ident, text);
            }
        }
        T::visit_dependencies(self);
        T::visit_generics(self);
    }
}

impl TypeVisitor for Collector {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        self.add::<T>();
    }
}

/// Types that cross the boundary without being a request or response of a row: the error envelope,
/// the job handle and the events of a job channel.
fn extra_roots(c: &mut Collector) {
    c.add::<ApiError>();
    c.add::<JobHandleDto>();
    c.add::<ProgressDto>();
    c.add::<JobEvent<Value>>();
    c.add::<JobResultEnvelope<Value>>();
    c.add::<DesignerMaterialMatrixRequest>();
    c.add::<MaterialMatrixDto>();
    c.add::<ModsSnapshot>();
}

struct Row {
    kind: &'static str,
    name: &'static str,
    request: String,
    response: String,
}

macro_rules! collect_rows {
    ($( $kind:ident $name:ident ( $_ctx:ident , $_req:ident : $req:ty ) -> $resp:ty = $path:path ; )*) => {
        fn collect_rows(c: &mut Collector) -> Vec<Row> {
            $( c.add::<$req>(); c.add::<$resp>(); )*
            vec![ $( Row {
                kind: stringify!($kind),
                name: stringify!($name),
                request: <$req as TS>::name(&c.cfg),
                response: <$resp as TS>::name(&c.cfg),
            }, )* ]
        }
    };
}

for_each_command!(collect_rows);

fn camel(name: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for ch in name.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

const HEADER: &str = "// Generated by `cargo test -p rimstudio-app --test bindings`. Do not edit.\n// Refresh: UPDATE_BINDINGS=1 cargo test -p rimstudio-app --test bindings\n\n";

fn render_bindings(c: &Collector) -> String {
    let mut out = String::from(HEADER);
    out.push_str("export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;\n");
    for (ident, decl) in &c.decls {
        if ident == "JsonValue" {
            continue;
        }
        out.push('\n');
        out.push_str(decl);
        out.push('\n');
    }
    out
}

/// The identifiers a type expression mentions, to build the import list of `commands.ts`.
fn identifiers(expr: &str) -> Vec<String> {
    let mut found = Vec::new();
    let mut word = String::new();
    for ch in expr.chars().chain(std::iter::once(' ')) {
        if ch.is_alphanumeric() || ch == '_' {
            word.push(ch);
        } else if !word.is_empty() {
            found.push(std::mem::take(&mut word));
        }
    }
    found
}

fn render_commands(c: &Collector, rows: &[Row]) -> String {
    let mut imports = BTreeSet::new();
    for row in rows {
        for expr in [&row.request, &row.response] {
            for word in identifiers(expr) {
                if c.decls.contains_key(&word) {
                    imports.insert(word);
                }
            }
        }
    }
    let mut out = String::from(HEADER);
    let list: Vec<String> = imports.into_iter().collect();
    let _ = writeln!(
        out,
        "import type {{\n  {},\n}} from \"./bindings\";\n",
        list.join(",\n  ")
    );
    out.push_str("/** How a command is wired: `query` and `action` answer inline, `job` returns a handle and ends with one terminal event, `stream` is a long lived channel. */\n");
    out.push_str("export type CommandKind = \"query\" | \"action\" | \"job\" | \"stream\";\n\n");
    out.push_str("/** Request, response and kind of every command. For a job the response is the result carried by its terminal event. */\n");
    out.push_str("export interface CommandTable {\n");
    for row in rows {
        let _ = writeln!(
            out,
            "  {}: {{ kind: \"{}\"; request: {}; response: {} }};",
            row.name, row.kind, row.request, row.response
        );
    }
    out.push_str("}\n\n");
    out.push_str("export type CommandName = keyof CommandTable;\n");
    out.push_str(
        "export type CommandRequest<N extends CommandName> = CommandTable[N][\"request\"];\n",
    );
    out.push_str(
        "export type CommandResponse<N extends CommandName> = CommandTable[N][\"response\"];\n",
    );
    out.push_str("export type CommandKindOf<N extends CommandName> = CommandTable[N][\"kind\"];\n");
    out.push_str("export type CommandsOfKind<K extends CommandKind> = {\n  [N in CommandName]: CommandKindOf<N> extends K ? N : never;\n}[CommandName];\n\n");
    out.push_str("/** One entry of the command list: the wire name and the kind. */\n");
    out.push_str("export interface CommandEntry<N extends CommandName = CommandName> {\n  readonly name: N;\n  readonly kind: CommandKindOf<N>;\n}\n\n");
    out.push_str("/** Every command by its camelCase export name. */\n");
    out.push_str("export const commands = {\n");
    for row in rows {
        let _ = writeln!(
            out,
            "  {}: {{ name: \"{}\", kind: \"{}\" }},",
            camel(row.name),
            row.name,
            row.kind
        );
    }
    out.push_str("} as const satisfies Record<string, CommandEntry>;\n\n");
    out.push_str("/** Every wire name, in registry order. */\n");
    out.push_str("export const commandNames = [\n");
    for row in rows {
        let _ = writeln!(out, "  \"{}\",", row.name);
    }
    out.push_str("] as const satisfies readonly CommandName[];\n");
    out
}

fn package_src() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../packages/ipc-types/src")
}

fn check_or_write(file: &str, text: &str) {
    let path = package_src().join(file);
    if std::env::var_os("UPDATE_BINDINGS").is_some() {
        std::fs::create_dir_all(package_src()).expect("create the package src folder");
        std::fs::write(&path, text).expect("write the bindings file");
        return;
    }
    let current = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        current == text,
        "{file} is stale or missing. Refresh with: {REFRESH}"
    );
}

fn generate() -> (String, String) {
    let mut c = Collector::new();
    let rows = collect_rows(&mut c);
    extra_roots(&mut c);
    (render_bindings(&c), render_commands(&c, &rows))
}

#[test]
fn committed_bindings_are_current() {
    let (bindings, commands) = generate();
    check_or_write("bindings.ts", &bindings);
    check_or_write("commands.ts", &commands);
}

#[test]
fn output_is_byte_stable() {
    assert_eq!(generate(), generate());
}

#[test]
fn every_row_is_in_the_table() {
    let mut c = Collector::new();
    let rows = collect_rows(&mut c);
    let names: Vec<&str> = rows.iter().map(|r| r.name).collect();
    let routes = rimstudio_app::registry::names();
    assert_eq!(names, routes);
    for needed in [
        "settings_get",
        "settings_update",
        "detect_run",
        "detect_get_report",
        "detect_set_override",
        "sources_list",
        "sources_add_folder",
        "sources_update",
        "sources_remove",
        "sources_probe_folder",
        "library_scan",
        "project_open",
        "project_create",
        "project_close",
        "project_tree",
        "project_layout_check",
        "project_scaffold_missing",
        "project_read_file",
        "defs_search",
        "defs_get_resolved",
        "designer_clone",
        "designer_clone_diff",
        "designer_structure_defaults",
        "designer_ce_suggest",
        "designer_quiz_back",
        "job_status",
        "cancel_job",
    ] {
        assert!(names.contains(&needed), "{needed} has no typed entry");
    }
}

/// Every public type of the contract crate is declared, so a type that is not reachable from a row
/// still shows up (add it to `extra_roots` or give it a reason here).
#[test]
fn every_contract_type_is_declared() {
    let mut c = Collector::new();
    collect_rows(&mut c);
    extra_roots(&mut c);
    let src = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../rimstudio-ipc-types/src");
    let mut missing = Vec::new();
    let mut stack = vec![src];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("read the source folder") {
            let path = entry.expect("entry").path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "rs") {
                let text = std::fs::read_to_string(&path).expect("read a source file");
                for line in text.lines() {
                    let rest = line
                        .strip_prefix("pub struct ")
                        .or_else(|| line.strip_prefix("pub enum "));
                    if let Some(rest) = rest {
                        let name: String = rest
                            .chars()
                            .take_while(|ch| ch.is_alphanumeric() || *ch == '_')
                            .collect();
                        if !c.decls.contains_key(&name) {
                            missing.push(name);
                        }
                    }
                }
            }
        }
    }
    missing.sort();
    assert!(
        missing.is_empty(),
        "types without a declaration: {missing:?}"
    );
}
