// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDirectory(arg1:string,arg2:string):Promise<string>;

export function CloseProject():Promise<main.AppBootstrap>;

export function CreateProject(arg1:main.CreateProjectInput):Promise<main.ProjectState>;

export function GetAppBootstrap():Promise<main.AppBootstrap>;

export function GetAvailableMods():Promise<Array<main.ScannedModSummary>>;

export function GetProjectState(arg1:string):Promise<main.ProjectState>;

export function OpenProject(arg1:string):Promise<main.ProjectState>;

export function RescanGameData():Promise<main.GameScanSnapshot>;

export function UpdateGlobalSettings(arg1:main.UpdateGlobalSettingsInput):Promise<main.AppBootstrap>;

export function UpdateProjectSettings(arg1:main.UpdateProjectSettingsInput):Promise<main.ProjectState>;
