// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory(arg1, arg2) {
  return window['go']['main']['App']['ChooseDirectory'](arg1, arg2);
}

export function CloseProject() {
  return window['go']['main']['App']['CloseProject']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function GetAppBootstrap() {
  return window['go']['main']['App']['GetAppBootstrap']();
}

export function GetAvailableMods() {
  return window['go']['main']['App']['GetAvailableMods']();
}

export function GetProjectState(arg1) {
  return window['go']['main']['App']['GetProjectState'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function RescanGameData() {
  return window['go']['main']['App']['RescanGameData']();
}

export function UpdateGlobalSettings(arg1) {
  return window['go']['main']['App']['UpdateGlobalSettings'](arg1);
}

export function UpdateProjectSettings(arg1) {
  return window['go']['main']['App']['UpdateProjectSettings'](arg1);
}
